name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js on Windows
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
    
    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install --legacy-peer-deps npx playwright install npm install

    # Step 4: Perform Build Check
    - name: Perform Build Check
      run: npm run build

    # Step 5: Run Unit Tests
    - name: Run Unit Tests
      run: npm test
