name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    # Step 4: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Step 5: Perform Build Check
    - name: Perform Build Check
      run: npm run build

    # Step 6: Start Development Server in the Background
    - name: Start Server
      run: |
        npm run dev &
        npx wait-on http://localhost:3000

    # Step 7: Run Unit Tests
    - name: Run Unit Tests
      run: npm test

    # Step 8: Run Playwright Tests
    - name: Run Playwright Tests
      run: npx playwright test
